Section_29/NBA_STATS/nba_stats_project/NBA/app/models/__init__.py
from .user_model import User

Section_29/NBA_STATS/nba_stats_project/NBA/app/models/user_model.py
from app.db import db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(UserMixin, db.Model):
    
    __tablename__ = 'users'
    
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)
    first_name = db.Column(db.String(50), nullable=False)
    last_name = db.Column(db.String(50), nullable=False)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

Section_29/NBA_STATS/nba_stats_project/NBA/app/forms/user_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log In')
    
class SignupForm(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

Section_29/NBA_STATS/nba_stats_project/NBA/app/__init__.py
from flask import Flask
from .views import main, user
from .db import connect_to_db
from .config import set_config, TestConfig
from flask_login import LoginManager

def create_app(testing=False):
    app = Flask(__name__)
    set_config(app)
    
    login_manager = LoginManager(app)
    
    
    with app.app_context():  
        connect_to_db(app, TestConfig if testing else None)
        
        login_manager.login_view = 'user.login'
        login_manager.login_message = 'Please log in to access this page.'
        
        from app.models.user_model import User
        
        @login_manager.user_loader
        def load_user(user_id):
            return User.query.get(int(user_id))
        
        app.register_blueprint(main)
        app.register_blueprint(user)
        
        return app
  
app = create_app()

Section_29/NBA_STATS/nba_stats_project/NBA/app/views/__init__.py
from .main import main
from .user import user

Section_29/NBA_STATS/nba_stats_project/NBA/app/views/main.py
from flask import Flask, render_template, Blueprint
from nba_api.stats.endpoints import *

main = Blueprint('main', __name__)

@main.route('/')
def home():
    
    return render_template('index.html')

@main.route('/leage_leaders')
def league_leaders():
    leaders = leagueleaders.LeagueLeaders().get_dict()
    leaders = leaders['resultSet']['rowSet']
    
    
    print(leaders)
    
    return render_template('league_leaders.html', league_leaders=leaders)

@main.route('/team_standings')
def team_standings():
    standings = leaguestandings.LeagueStandings().get_dict()
    standings = standings['resultSets'][0]['rowSet']
    
    return render_template('team_standings.html', team_standings=standings)

Section_29/NBA_STATS/nba_stats_project/NBA/app/views/user.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import current_user, login_user, logout_user, login_required
from app.models.user_model import User
from app.forms.user_form import LoginForm, SignupForm
from app.db import db

user = Blueprint('user', __name__)

@user.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
      
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(form.password.data):
            login_user(user)
            flash('Logged in successfully.', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Invalid email or password.', 'danger')
    
    return render_template('login.html', form=form)

  
@user.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
      
    form = SignupForm()
    if form.validate_on_submit():
        user = User(
            email=form.email.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data
        )
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        # Redirect to the homepage 
        flash('Account created successfully.', 'success')
        return redirect(url_for('user.login'))
      
    return render_template('signup.html', form=form)

@user.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logged out successfully.', 'success')
    return redirect(url_for('user.login'))
  
@user.route('/account')
@login_required
def account():
    return render_template('account.html', user=current_user)

Section_29/NBA_STATS/nba_stats_project/NBA/app/templates/account.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
  <div class="container">
    <h1>Welcome, {{ user.username }}!</h1>
    <p>Email: {{ user.email }}</p>
    <a href="{{ url_for('user.logout') }}" class="btn btn-primary">Logout</a>
  </div>
{% endblock %}

Section_29/NBA_STATS/nba_stats_project/NBA/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="static/base.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('main.home') }}">NBA HUB</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link {% if request.path == url_for('main.home') %}active{% endif %}" href="{{ url_for('main.home') }}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path == url_for('main.league_leaders') %}active{% endif %}" href="{{ url_for('main.league_leaders') }}">League Leaders</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path == url_for('main.team_standings') %}active{% endif %}" href="{{ url_for('main.team_standings') }}">League Standings</a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('user.account') }}">Account</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('user.logout') }}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('user.login') }}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('user.signup') }}">Signup</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      {% block content %}{% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

Section_29/NBA_STATS/nba_stats_project/NBA/app/templates/index.html
{% extends 'base.html' %}

{% block title %}Home {%endblock%}

{% block content %}
  <h1>Home</h1>
      {% with messages = get_flashed_messages() %}
      {% if messages %}
        <ul class="messages">
          {% for message in messages %}
            <li>{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
{% endblock %}
```

Section_29/NBA_STATS/nba_stats_project/NBA/app/templates/league_leaders.html
{% extends 'base.html' %}
{% block title %}League Leaders{% endblock %}

{% block content %}
  <h1 class="text-center my-3">League Leaders</h1>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Player</th>
        <th>Team</th>
        <th>GP</th>
        <th>MIN</th>
        <th>FGM</th>
        <th>FGA</th>
        <th>FG %</th>
        <th>3PM</th>
        <th>3PA</th>
        <th>3P %</th>
        <th>FTM</th>
        <th>FTA</th>
        <th>FT %</th>
        <th>OREB</th>
        <th>DREB</th>
        <th>REB</th>
        <th>AST</th>
        <th>STL</th>
        <th>BLK</th>
        <th>TOV</th>
        <th>PF</th>
        <th>PTS</th>
      </tr>
    </thead>
    <tbody>
      {% for player in league_leaders %}
        <tr>
          <td>{{ player[2] }}</td>
          <td>{{ player[4] }}</td>
          <td>{{ player[5] }}</td>
          <td>{{ player[6] }}</td>
          <td>{{ player[7] }}</td>
          <td>{{ player[8] }}</td>
          <td>{{ player[9] }}</td>
          <td>{{ player[10] }}</td>
          <td>{{ player[11] }}</td>
          <td>{{ player[12] }}</td>
          <td>{{ player[13] }}</td>
          <td>{{ player[14] }}</td>
          <td>{{ player[15] }}</td>
          <td>{{ player[16] }}</td>
          <td>{{ player[17] }}</td>
          <td>{{ player[18] }}</td>
          <td>{{ player[19] }}</td>
          <td>{{ player[20] }}</td>
          <td>{{ player[21] }}</td>
          <td>{{ player[22] }}</td>
          <td>{{ player[23] }}</td>
          <td>{{ player[24] }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

Section_29/NBA_STATS/nba_stats_project/NBA/app/templates/login.html
{% extends 'base.html' %}

{% block title %}
  Login
{% endblock %}

{% block content %}
  <div class="container">
    <h1>Login</h1>
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <ul class="messages">
          {% for message in messages %}
            <li>{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
    <form method="POST" action="{{ url_for('user.login') }}">
      {{ form.hidden_tag() }}
       
      
      <div class="mb-3">
        <label for="email" class="form-label">Email:</label>
        <input type="email" id="email" name="email" class="form-control" required>
      </div>
      <div class="mb-3">
        <label for="password" class="form-label">Password:</label>
        <input type="password" id="password" name="password" class="form-control" required>
      </div>
      <button type="submit" class="btn btn-primary">Log in</button>
    </form>
  </div>
{% endblock %}

Section_29/NBA_STATS/nba_stats_project/NBA/app/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
    <div class="container">
        <h1>Sign Up</h1>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}
        <form method="POST" action="{{ url_for('user.signup') }}">
            {{ form.hidden_tag() }}
            
            <div class="mb-3">
                <label for="email" class="form-label">Email:</label>
                {{ form.email(class="form-control", required=True) }}
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Password:</label>
                {{ form.password(class="form-control", required=True) }}
            </div>
            <div class="mb-3">
                <label for="confirm_password" class="form-label">Confirm Password:</label>
                {{ form.confirm_password(class="form-control", required=True) }}
            </div>
            <div class="mb-3">
                <label for="first_name" class="form-label">First Name:</label>
                {{ form.first_name(class="form-control", required=True) }}
            </div>
            <div class="mb-3">
                <label for="last_name" class="form-label">Last Name:</label>
                {{ form.last_name(class="form-control", required=True) }}
            </div>
            <button type="submit" class="btn btn-primary">Sign Up</button>
        </form>
    </div>
{% endblock %}

Section_29/NBA_STATS/nba_stats_project/NBA/app/templates/team_standings.html
{% extends 'base.html' %}
{% block title %}Team Standings{% endblock %}

{% block content %}
  <h1 class="text-center my-3">League Standings</h1>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Team</th>
        <th>Record</th>
        <th>Conference</th>
        <th>Division</th>
        <th>League Rank</th>
      </tr>
    </thead>
    <tbody>
      {% for team in team_standings %}
        <tr>
          <td>{{ team[3] }} {{team[4]}}</td>
          <td>{{ team[16] }}</td>
          <td>{{ team[6] }}</td>
          <td>{{ team[10] }}</td>
          <td>{{ team[15] }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}